name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Verify Bun
        run: bun --version

      - name: Install
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bun run typecheck

      - name: Test
        run: bun test --ci

      - name: Build
        run: bun run build
