name: Release (tag -> npm)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          github-token: ${{ secrets.GH_TOKEN || github.token }}

      - name: Verify Bun
        run: bun --version

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      # 🔐 Write npm auth to ~/.npmrc explicitly
      - name: Configure npm auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

      - name: Publish to npm
        run: npm publish --access public
