name: Release (tag -> npm)

on:
  push:
    tags:
      - "v*" # e.g. v0.0.15
  workflow_dispatch: {}

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed for creating the GitHub Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          # prefer your custom secret, fall back to the built-in token
          github-token: ${{ secrets.GH_TOKEN || github.token }}

      - name: Verify Bun
        run: bun --version

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
