name: Release (tag -> npm via OIDC)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # create GitHub Release
      id-token: write # <-- required for npm OIDC
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      # OIDC auth to npm (no token)
      - name: Setup Node for npm (OIDC)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

      - name: Publish to npm with provenance
        run: npm publish --access public --provenance
